# -*- coding: utf-8 -*-
"""spacy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PvWiuiOWi9TFTT6hZQJrobxF87dT5LBY
"""

!pip3 install spacy

import spacy
import time

nlp=spacy.load('en')  # this will use nltk_data folder to load library

data="i am doing great sometimes then i use feet to do not know"

# applying NLP --means tkonizing itself
process_data=nlp(data)

for i in process_data:
  print(i,"--->finding lemma->",i.lemma_)
  time.sleep(2)
  print("pos of word is: ",i.pos_)

